### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by fedepalu2** [ComfyWorkflows/ComfyUI-Launcher#9]
Following the steps of Manual setup (Option 2)
chmod +x run.sh is not a dos command
./run.sh is not working

**Comment by thecooltechguy** [comment]
hi @fedepalu2 , to confirm, are you running the commands in the WSL (Windows Subsystem for Linux) terminal? Note: this is separate from Window's default Command Line Prompt.

thanks!

**Comment by fedepalu2** [comment]
ok you are right, I will intall WSL and give you feedback!

**Comment by fedepalu2** [comment]
Is little bit complex, I have a new installation of WSL, i should or install docker (i never did) or go to manual setup but I have to first install python, pip, etc. Is becoming difficoult...

**Comment by dylanintech** [comment]
hey @fedepalu2 - can you please try following the instructions in this new branch for windows installation support:
https://github.com/ComfyWorkflows/ComfyUI-Launcher/tree/new-docker-setup

**Comment by fedepalu2** [comment]
Ok I could install but after some frustration because no space available i managed by monut a virtual disk and force Docker to use that disk, I could import the workflow but after Comfyui doesen't start, the browser says localhost:4001 ERR_CONNECTION_REFUSED

Also docker consume most of the ram and is not good. Tomorrow I will do more test.

**Comment by dylanintech** [comment]
> Ok I could install but after some frustration because no space available i managed by monut a virtual disk and force Docker to use that disk, I could import the workflow but after Comfyui doesen't start, the browser says localhost:4001 ERR_CONNECTION_REFUSED
> 
> Also docker consume most of the ram and is not good. Tomorrow I will do more test.

thank you for testing @fedepalu2 - can you please tell me what error you're seeing in the terminal after clicking the "launch" button on a project? this would let me know how to fix this issue.

**Comment by dylanintech** [comment]
hey @fedepalu2  - new update! we just pushed a fix to the [new-docker-setup](https://github.com/ComfyWorkflows/ComfyUI-Launcher/tree/new-docker-setup) branch. if you follow the instructions (option 1: docker) on that branch's README, you should be able to get the launcher to work! thank you for your patience - let me know if it works and if this issue should be closed!

**Comment by fedepalu2** [comment]
When docker is running the pc become very sloowly, further if i restart I have to reimport the workflow and download all the model, that take too much time. Still is not working... seems not viable for me.

**Comment by thecooltechguy** [comment]
@fedepalu2 just wanted to update that we've updated this repo's main branch to have all the fixes necessary for windows + docker

First, you can update to the latest docker image, with this commands:

```
docker pull thecooltechguy/comfyui_launcher 
```

and then to start docker, you can run:

```
docker run ^
--gpus all ^ # remove this line if you don't have a GPU
--rm ^
--name comfyui_launcher ^
-p 4000-4100:4000-4100 ^
-v %cd%/comfyui_launcher_models:/app/server/models ^
-v %cd%/comfyui_launcher_projects:/app/server/projects ^
-it thecooltechguy/comfyui_launcher
```

Btw, all workflows are saved, so when you restart, you won't have to re-download any models or re-import any workflows.

If the latest update is still not working for you, can you kindly share a short screen recording of what you are trying and how it is not working? thank you so much for your help with this!

**Comment by thecooltechguy** [comment]
Closing due to no response, feel free to re-open anytime!

**Comment by fedepalu2** [comment]
I'm again trying to use it. What means "Use a static port" in the import dialog?

**Comment by fedepalu2** [comment]
what to do? (i don't post all the json because is veri long https://comfyworkflows.com/workflows/fc39dabc-9727-4067-bac7-dcd8ef02ac13)

172.17.0.1 - - [13/Mar/2024 09:19:33] "GET /api/settings HTTP/1.1" 200 -
172.17.0.1 - - [13/Mar/2024 09:19:33] "GET /api/projects HTTP/1.1" 200 -
172.17.0.1 - - [13/Mar/2024 09:19:36] "GET /import HTTP/1.1" 200 -
172.17.0.1 - - [13/Mar/2024 09:19:36] "GET /assets/index-BcHurkhF.css HTTP/1.1" 304 -
172.17.0.1 - - [13/Mar/2024 09:19:36] "GET /assets/index-B7I_54js.js HTTP/1.1" 304 -
172.17.0.1 - - [13/Mar/2024 09:19:36] "GET /api/settings HTTP/1.1" 200 -
Detected workflow json format, converting to launcher json format
[2024-03-13 09:20:04,625] ERROR in app: Exception on /api/import_project [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/server/server.py", line 233, in import_project
    res = get_launcher_json_for_workflow_json(import_json, resolved_missing_models, skip_model_validation)
  File "/app/server/utils.py", line 384, in get_launcher_json_for_workflow_json
    response.status_code == 200 or response.status_code == 400
AssertionError: Failed to get launcher json for workflow json:...... [...] 
172.17.0.1 - - [13/Mar/2024 09:20:04] "POST /api/import_project HTTP/1.1" 500 -
